if(NOT DEFINED DEVICEEXPLORER_SOURCE_ROOT OR NOT DEFINED DEVICEEXPLORER_BUILD_ID_HEADER OR
   NOT DEFINED DEVICEEXPLORER_BUILD_ID_HEADER_DIR)
    message(FATAL_ERROR "source root, output header, and output directory are required")
endif()

if(DEFINED DEVICEEXPLORER_BUILD_ID_OVERRIDE AND NOT DEVICEEXPLORER_BUILD_ID_OVERRIDE STREQUAL "")
    set(DEVICEEXPLORER_BUILD_ID "${DEVICEEXPLORER_BUILD_ID_OVERRIDE}")
else()
    execute_process(
        COMMAND git rev-parse --short=12 HEAD
        WORKING_DIRECTORY "${DEVICEEXPLORER_SOURCE_ROOT}"
        OUTPUT_VARIABLE DEVICEEXPLORER_BUILD_ID
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE DEVICEEXPLORER_GIT_RESULT
    )
    if(NOT DEVICEEXPLORER_GIT_RESULT EQUAL 0 OR DEVICEEXPLORER_BUILD_ID STREQUAL "")
        set(DEVICEEXPLORER_BUILD_ID "unknown")
    else()
        execute_process(
            COMMAND git status --porcelain --untracked-files=normal
            WORKING_DIRECTORY "${DEVICEEXPLORER_SOURCE_ROOT}"
            OUTPUT_VARIABLE DEVICEEXPLORER_DIRTY_STATE
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        if(NOT DEVICEEXPLORER_DIRTY_STATE STREQUAL "")
            string(APPEND DEVICEEXPLORER_BUILD_ID "-dirty")
        endif()
    endif()
endif()

file(MAKE_DIRECTORY "${DEVICEEXPLORER_BUILD_ID_HEADER_DIR}")
set(DEVICEEXPLORER_TEMP_HEADER "${DEVICEEXPLORER_BUILD_ID_HEADER}.tmp")
file(WRITE "${DEVICEEXPLORER_TEMP_HEADER}"
    "#pragma once\n#define DEVICEEXPLORER_BUILD_ID \"${DEVICEEXPLORER_BUILD_ID}\"\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
    "${DEVICEEXPLORER_TEMP_HEADER}" "${DEVICEEXPLORER_BUILD_ID_HEADER}")
file(REMOVE "${DEVICEEXPLORER_TEMP_HEADER}")
