#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"

#include "DeviceExplorerSettings.generated.h"

UCLASS(Config = Engine, DefaultConfig, meta = (DisplayName = "DeviceExplorer (Project)"))
class DEVICEEXPLORER_API UDeviceExplorerSettings final : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	virtual FName GetCategoryName() const override { return TEXT("Plugins"); }

	/**
	 * Shared secret for the device link, generated by the Editor on first use. It is
	 * packaged into every build made from this project, so anyone holding the project or
	 * one of its builds can reach a host running this token. Clear it to fall back to a
	 * token per host session, passed with -DeviceExplorerToken.
	 */
	UPROPERTY(Config, EditAnywhere, Category = "Security")
	FString SessionToken;
};
